name: lighthouse
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
        npm run build
    - name: Run lighthouse
      run: |
        npm install -g @lhci/cli@0.7.x
        lhci autorun